let
    ソース = Table.Combine({#"2023年度（～11月）00390104_FKAC167_20240205215306_1", #"2022年度　00390104_FKAC167_20240124213507_1", #"2021年度　00390104_FKAC167_20220520213623_1", #"2020年度　00390104_FKAC167_20210913213400_1", #"2019年度　00390104_FKAC167_20210204213406_1"}),
    表示= Table.SelectColumns(ソース, {"個人番号","健診実施年月日","身長","体重","ＢＭＩ","収縮期血圧","拡張期血圧","中性脂肪（トリグリセリド）","ＨＤＬコレステロール","ＬＤＬコレステロール","GOT（ＡＳＴ）","GPT（ＡＬＴ）","γ-GT(γ-GTP)","空腹時血糖（電位差法）","ＨｂＡ１ｃ（NGSP値）","尿糖","尿蛋白"}),
    #"尿蛋白 不備削除" = Table.SelectRows(表示, each [尿蛋白] <> null and [尿蛋白] <> ""),
    #"尿糖 不備削除" = Table.SelectRows(#"尿蛋白 不備削除", each [尿糖] <> null and [尿糖] <> ""),
    血糖値評価 = Table.AddColumn(#"尿糖 不備削除", "血糖値評価", each if (([#"空腹時血糖（電位差法）"] = null or [#"空腹時血糖（電位差法）"] = "") and ([#"ＨｂＡ１ｃ（NGSP値）"] = null or [#"ＨｂＡ１ｃ（NGSP値）"] = "")) then false else true),
    フィルターされた行 = Table.SelectRows(血糖値評価, each [健診実施年月日] <= 20231130)
in
    フィルターされた行
