let
    ソース = Csv.Document(File.Contents("\\192.168.12.41\d\jmdc-share\個人通知\SI作業用\R7（FY25）\健康年齢\01_秋田県鹿角市\2_秋田県鹿角市_作業中\台帳\Cun_m1065_20250519152434326.csv"),[Delimiter=",", Columns=91, Encoding=932, QuoteStyle=QuoteStyle.None]),
    昇格されたヘッダー数 = Table.PromoteHeaders(ソース, [PromoteAllScalars=true]),
    変更された型 = Table.TransformColumnTypes(昇格されたヘッダー数,{{"自治体ｺｰﾄﾞ", Int64.Type}, {"保険証番号", Int64.Type}, {"宛名番号", type number}, {"CPU連番", Int64.Type}, {"国保資格区分", Int64.Type}, {"国保資格区分名称", type text}, {"国保履歴番号", Int64.Type}, {"初期登録業務日時", type number}, {"更新業務日時", type number}, {"更新ｼｽﾃﾑ日時", type number}, {"更新ｺﾝﾋﾟｭｰﾀ名", type text}, {"更新ﾕｰｻﾞID", type text}, {"国保有効ﾌﾗｸﾞ", Int64.Type}, {"決裁状態", Int64.Type}, {"旧自治体ｺｰﾄﾞ", Int64.Type}, {"文字列型予備項目1", type text}, {"保険証番号内連番", Int64.Type}, {"適用開始事由国保異動事由", Int64.Type}, {"国保異動事由ｺｰﾄﾞ名称01", type text}, {"適用開始国保異動区分", Int64.Type}, {"適用開始異動年月日", Int64.Type}, {"適用開始届出年月日", Int64.Type}, {"適用開始時効年月日", Int64.Type}, {"適用終了事由国保異動事由", type text}, {"国保異動事由ｺｰﾄﾞ名称02", type text}, {"適用終了国保異動区分", type text}, {"適用終了異動年月日", type text}, {"適用終了届出年月日", type text}, {"適用終了時効年月日", type text}, {"続柄ｺｰﾄﾞ", Int64.Type}, {"記載順位", Int64.Type}, {"次CPU連番", Int64.Type}, {"前CPU連番", Int64.Type}, {"国保世帯最新ﾌﾗｸﾞ", Int64.Type}, {"国保個人最新ﾌﾗｸﾞ", Int64.Type}, {"抹消ﾌﾗｸﾞ", Int64.Type}, {"旧保険証番号", type text}, {"保険証番号結合処理年月日", type text}, {"保険証番号結合ｺﾝﾋﾟｭｰﾀ名", type text}, {"保険証番号結合ﾕｰｻﾞ名", type text}, {"旧宛名番号", type text}, {"宛名番号結合処理年月日", type text}, {"宛名番号結合ｺﾝﾋﾟｭｰﾀ名", type text}, {"宛名番号結合ﾕｰｻﾞ名", type text}, {"適用開始旧被扶養者区分", Int64.Type}, {"適用終了旧被扶養者区分", Int64.Type}, {"給付開始年月日", Int64.Type}, {"枝番", Int64.Type}, {"宛名住民区分", Int64.Type}, {"宛名住民区分ｺｰﾄﾞ短名称", type text}, {"個人法人区分", Int64.Type}, {"宛名世帯番号", type number}, {"編集済氏名漢字", type text}, {"編集済氏名ｶﾅ", type text}, {"現住所郵便番号1", Int64.Type}, {"現住所ｺｰﾄﾞ", type number}, {"現住所県名付加区分", Int64.Type}, {"現住所", type text}, {"現住所地番", type text}, {"現住所方書漢字", type text}, {"転入前住所郵便番号", Int64.Type}, {"転入前住所ｺｰﾄﾞ", type number}, {"転入前住所", type text}, {"転入前住所地番", type text}, {"転入前住所方書漢字", type text}, {"宛名郵便番号", Int64.Type}, {"宛名住所ｺｰﾄﾞ", type number}, {"宛名県名付加区分", Int64.Type}, {"宛名住所", type text}, {"宛名地番", type text}, {"宛名方書漢字", type text}, {"宛名地番数値1", Int64.Type}, {"宛名地番数値2", Int64.Type}, {"宛名地番数値3", Int64.Type}, {"宛名生年月日", Int64.Type}, {"宛名年齢", Int64.Type}, {"性別区分", Int64.Type}, {"性別区分ｺｰﾄﾞ短名称", type text}, {"宛名行政区ｺｰﾄﾞ", Int64.Type}, {"宛名消除区分", Int64.Type}, {"宛名続柄ｺｰﾄﾞ", Int64.Type}, {"宛名異動事由ｺｰﾄﾞ", Int64.Type}, {"宛名異動日", Int64.Type}, {"宛名異動届出日", Int64.Type}, {"宛名増減事由ｺｰﾄﾞ", Int64.Type}, {"宛名増減異動日", Int64.Type}, {"国籍ｺｰﾄﾞ", type text}, {"国籍名", type text}, {"在留資格ｺｰﾄﾞ", type text}, {"在留資格名称", type text}, {"在留期限日", type text}}),
    削除された他の列 = Table.SelectColumns(変更された型,{"宛名番号", "編集済氏名漢字", "編集済氏名ｶﾅ", "宛名郵便番号", "宛名住所", "宛名地番", "宛名方書漢字"}),
    追加されたカスタム = Table.AddColumn(削除された他の列, "編集住所", each [宛名住所]&[宛名地番]&" "&[宛名方書漢字]),
    追加されたカスタム1 = Table.AddColumn(追加されたカスタム, "資格取得日", each 20240402),
    追加されたカスタム2 = Table.AddColumn(追加されたカスタム1, "資格喪失日", each ""),
    挿入されたテキストの長さ = Table.AddColumn(追加されたカスタム2, "文字数", each Text.Length([編集済氏名漢字]), Int64.Type),
    挿入されたテキストの長さ1 = Table.AddColumn(挿入されたテキストの長さ, "文字数 カナ", each Text.Length([編集済氏名ｶﾅ]), Int64.Type),
    削除された他の列1 = Table.SelectColumns(挿入されたテキストの長さ1,{"宛名番号", "編集済氏名漢字", "編集済氏名ｶﾅ", "宛名郵便番号", "編集住所", "資格取得日", "資格喪失日", "文字数", "文字数 カナ"})
in
    削除された他の列1